### ISSUE TITLE
IndexError: list index out of range while downloading videos.

### ISSUE THREAD

**Issue by vineetasharma** [przemyslawpluta/node-youtube-dl#127]
{ Error: Command failed: /home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.msnbc.com/all-in/watch/fl-sen-we-ve-seen-the-good-times-and-the-bad-780910147946
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/**init**.py", line 434, in main
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/**init**.py", line 424, in _real_main
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1788, in download
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 702, in extract_info
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in process_ie_result
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 373, in _real_extract
  File "/home/ttnd/Veritone/youtube-adapter/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 309, in _extract_feed_info
IndexError: list index out of range

its causing while downloading videos from url: http://www.msnbc.com/all-in/watch/fl-sen-we-ve-seen-the-good-times-and-the-bad-780910147946

**Comment by vineetasharma** [comment]
+1
