### ISSUE TITLE
Error: Path must be a string

### ISSUE THREAD

**Issue by f4th4n** [przemyslawpluta/node-youtube-dl#142]
I got error when I tried to run example/audio.js

```
$ node index.js 
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.<anonymous> (/home/fathan/work/node_modules/youtube-dl/lib/youtube-dl.js:19:71)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

OS: Ubuntu 16.10
Node: v7.8.0
package youtube-dl version: 1.11.1
youtube-dl binary version: 2017.04.03

**Comment by hqxluoyang** [comment]
i  am

**Comment by Kittenji** [comment]
TypeError: Path must be a string. Received undefined
It's broken
