### ISSUE TITLE
Can't change working directory.

### ISSUE THREAD

**Issue by FireController1847** [przemyslawpluta/node-youtube-dl#144]
Hia! I've been trying to change my cwd (current working directory), but the file keeps being created in the same spot. Some help would be appreciated.

```js
const youtubedl = require("youtube-dl");
var video = youtubedl("https://www.youtube.com/watch?v=7wNb0pHyGuI", ['-x', '--audio-format', 'mp3'], { cwd: __dirname + "/API/Sessions"});
video.on('info', function(info) {
  console.log('Download started');
  console.log('filename: ' + info.filename);
  console.log('size: ' + info.size);
});
video.pipe(fs.createWriteStream('myvideo.mp3'));
```

I'm trying to get the file to create in "./API/Sessions", but it's still being created in "./" Please help soon!

**Comment by FireController1847** [comment]
Just noticing this in logs now. Seems to be a lib issue.
```
8|Discedia | events.js:163
8|Discedia |       throw er; // Unhandled 'error' event
8|Discedia |       ^
8|Discedia | Error: spawn /root/node_modules/youtube-dl/bin/youtube-dl ENOENT
8|Discedia |     at exports._errnoException (util.js:1050:11)
8|Discedia |     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
8|Discedia |     at onErrorNT (internal/child_process.js:367:16)
8|Discedia |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
8|Discedia |     at process._tickCallback (internal/process/next_tick.js:104:9)
```
