### ISSUE TITLE
Error: Could not find download link

### ISSUE THREAD

**Issue by acarl005** [przemyslawpluta/node-youtube-dl#162]
```
$ npm i youtube-dl

> youtube-dl@1.11.1 postinstall /Users/andy/Documents/stem/alpha/node_modules/youtube-dl
> node ./scripts/download.js

Error: Could not find download link in https://rg3.github.io/youtube-dl/download.html
    at Request.get [as _callback] (/Users/andy/Documents/stem/alpha/node_modules/youtube-dl/lib/downloader.js:64:31)
    at Request.self.callback (/Users/andy/Documents/stem/alpha/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/andy/Documents/stem/alpha/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/andy/Documents/stem/alpha/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
stem-api@2017.8.4-production1 /Users/andy/Documents/stem/alpha
└── youtube-dl@1.11.1

$ node -v
v7.9.0
$ npm -v
4.2.0
```

**Comment by acarl005** [comment]
Also tried on node 8.1.3 and npm 5.4.1. Same error.

**Comment by acarl005** [comment]
Pushed a fix in PR #163.

**Comment by acarl005** [comment]
If anyone else is desperate for a fix, you can install [our fork](https://github.com/stems/node-youtube-dl). It's published under the package name `@stem/youtube-dl` in NPM.

**Comment by mayeaux** [comment]
Maybe we should start maintaining this repo on your fork? Not sure if anyone can get ahold of this guy

**Comment by przemyslawpluta** [comment]
@acarl005 @mayeaux please test latest should be fine and thanks for all the fixes so far.

**Comment by Sivitas** [comment]
is the new code going to be deployed as a new version? npm hasn't been updated since April 2016
