### ISSUE TITLE
"ERROR: ffprobe or avprobe not found."

### ISSUE THREAD

**Issue by SpectralKH** [przemyslawpluta/node-youtube-dl#166]
I seem to be getting an error when running the audio.js example. I am running Docker's node:8.6 image.

Log:
```
Error: Command failed: /node_modules/youtube-dl/bin/youtube-dl -x --audio-format mp3 http://www.youtube.com/watch?v=dvsOfsMlT3M
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
ERROR: ffprobe or avprobe not found. Please install one.

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Code:
```
const ytdl = require('youtube-dl');
const url = "https://www.youtube.com/watch?v=dvsOfsMlT3M";
ytdl.exec(url, ["-x", "--audio-format", "mp3"], {}, function exec(err, output) {
    "use strict";
    if (err) {
        throw err;
    }
    console.log(output.join("\n"));
});
```

**Comment by SpectralKH** [comment]
I am stupid :)
