### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by Delivator** [przemyslawpluta/node-youtube-dl#168]
Code:
```js
const fs = require("fs");
const youtubedl = require("youtube-dl");
const crypto = require("crypto");

let url = "https://www.youtube.com/watch?v=i9FplMA4gGA";
let fileName = crypto.createHash("md5").update(url).digest("hex");
if (fs.existsSync(`${fileName}`)) return callback(fileName);

let  video = youtubedl(url, ["-x", "--format=bestaudio", "--audio-format=mp3"], { cwd: __dirname});

video.on("end", function() {
  let fileSize = fs.statSync(`${fileName}`)["size"] / 1048576;
  console.log(`[YTDL] Download of "${fileName}" finished! Filesize: ${String(fileSize).substring(0, 4)} MiB`);
  return callback(fileName);
});

console.log(`[YTDL] Downloading file "${url}" to ".cache/${fileName}"`);
video.pipe(fs.createWriteStream(`{fileName}`));
```

Error in console:
```
PS C:\Users\Delivator\Desktop\fhjhjffhj> node .\test.js
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at exports.execFile (child_process.js:208:15)
    at call (C:\Users\Delivator\Desktop\fhjhjffhj\node_modules\youtube-dl\lib\youtube-dl.js:163:5)
    at Function.getInfo (C:\Users\Delivator\Desktop\fhjhjffhj\node_modules\youtube-dl\lib\youtube-dl.js:285:5)
    at module.exports (C:\Users\Delivator\Desktop\fhjhjffhj\node_modules\youtube-dl\lib\youtube-dl.js:107:10)
    at Object.<anonymous> (C:\Users\Delivator\Desktop\fhjhjffhj\test.js:9:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

This error just appeared after updating to the newest version.

**Comment by Delivator** [comment]
After some testing I found out that the youtube-dl version which is beeing download is either corrupt or a verry old version.

youtube-dl.exe file in the bin folder (`node_modules/youtube-dl/bin/youtube-dl.exe`):
Size: 1.51 MB
SHA1: D0818378D3C203F9B081CCC0B8183E7D138131DF
Version (details file): 2017.10.12

youtube-dl.exe from github (Version 2017.10.12)
Size: 7.44 MB
SHA1: 15F78889A60812264BC888869AD744F16AB0696A

**Comment by Delivator** [comment]
Okay looks like the latest youtube-dl build is just broke (2017.10.12). Filesize: 1.51 MB on GitHub

**Comment by p4c0** [comment]
@Delivator thank you very much !! Spend hours to try to figure out what was the matter. I just replace the wrong executable in my [project]\node_modules\youtube-dl\bin with the good one on youtube-dl site. thanks !!
