### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by 27therealone** [przemyslawpluta/node-youtube-dl#173]
Each time i try to console.log a .getInfo i get this error: 
{ Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:323:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:235:13)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
  cmd: '/root/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --no-warnings --force-ipv4 ytsearch: rockstar post malone' }

**Comment by KarboniteKream** [comment]
See #126.

**Comment by DuBistKomisch** [comment]
This could be fixed by using `spawn` instead of `exec` and buffering the output internally, instead of making everyone use a workaround.

**Comment by Kikobeats** [comment]
I'm happy to address this error. 

I feel that using [execa](https://github.com/sindresorhus/execa#execa---) should be enough, it has sensible good defaults.

What do you think?
