### ISSUE TITLE
Error getting information about youtube video. 

### ISSUE THREAD

**Issue by ajitgoel** [przemyslawpluta/node-youtube-dl#186]
i am running the following code to get the information about a youtube video and i get an error. what am i missing? 

**StackTrace**:
Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: spawn UNKNOWN
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: spawn UNKNOWN
    at callFunction (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at callFunction (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:234:13)
    at Object.remoteMemberFunction (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:118:18)
    at YouTubeDownloaderForm.handleAddClick (<anonymous>:65:19)
    at HTMLUnknownElement.callCallback (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:580:14)
    at Object.invokeGuardedCallbackDev (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:619:16)
    at Object.invokeGuardedCallback (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:476:27)
    at Object.invokeGuardedCallbackAndCatchFirstError (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:490:43)
    at executeDispatch (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:972:19)
    at executeDispatchesInOrder (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:994:5)
    at executeDispatchesAndRelease (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:1092:5)

```**Code:** 
var youtubedl = require('youtube-dl');
var url = 'http://www.youtube.com/watch?v=WKsjaOqDXgg';
// Optional arguments passed to youtube-dl.
var options = [];
youtubedl.getInfo(url, options, function(err, info) {
  if (err) throw err;
  console.log('id:', info.id);
  console.log('title:', info.title);
  console.log('url:', info.url);
  console.log('thumbnail:', info.thumbnail);
  console.log('description:', info.description);
  console.log('filename:', info._filename);
  console.log('format id:', info.format_id);
});
```

**Comment by ajitgoel** [comment]
I fixed it by download the latest youtube-dl exe from https://youtube-dl.org/downloads/latest/youtube-dl.exe, then putting it in node_modules\youtube-dl\bin
please close this issue.
