### ISSUE TITLE
download youtube url as file

### ISSUE THREAD

**Issue by ajitgoel** [przemyslawpluta/node-youtube-dl#189]
I am using the following code to download a youtube url as a file but throws an exception. What am I missing?
```
var youtubedl = youtubedl('http://www.youtube.com/watch?v=90AiXO1pAiA',
    ['--format=18'],
    { cwd: __dirname });
  
  // Will be called when the download starts.
  youtubedl.on('info', function(info) 
  {
    console.log('Download started');
    console.log('filename: ' + info.filename);
    console.log('size: ' + info.size);
  });  
  youtubedl.pipe(fs.createWriteStream('myvideo.mp4'));
```

StackTrace: ```
Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: youtubedl is not a function
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: youtubedl is not a function
    at callFunction (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at callFunction (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:234:13)
    at Object.remoteMemberFunction (C:\temp\Electron\YouTubeDownloader\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:118:18)
    at handleDownload (<anonymous>:90:19)
    at HTMLUnknownElement.callCallback (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:580:14)
    at Object.invokeGuardedCallbackDev (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:619:16)
    at Object.invokeGuardedCallback (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:476:27)
    at Object.invokeGuardedCallbackAndCatchFirstError (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:490:43)
    at executeDispatch (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:972:19)
    at executeDispatchesInOrder (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:994:5)
    at executeDispatchesAndRelease (https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js:1092:5)
```

**Comment by invisibletank** [comment]
Try not naming your variable "youtubedl".  The example uses "var video = youtubedl(...)"
