### ISSUE TITLE
Error on require('youtube-dl')

### ISSUE THREAD

**Issue by T0k3n** [przemyslawpluta/node-youtube-dl#197]
Hi, since yesterday I've been encountering the following error in `const ytdl = require('youtube-dl');`

```
path.js:39
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:1331:5)
    at Object.<anonymous> (/rbd/pnpm-volume/3915dc4d-a3c0-4a33-8f21-d0d2fa1de054/node_modules/.registry.npmjs.org/youtube-dl/1.12.2/node_modules/youtube-dl/lib/youtube-dl.js:21:73)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```

This was never an issue before. I'm using version 1.12.2 , but the issue doesn't resolve itself when I roll back to earlier versions. Any help is appreciated.

**Comment by T0k3n** [comment]
Huh, that's strange. The issue resolved itself after a few days without any changes on my side. Might have been a problem in the package manager itself, so I'm closing this issue.

**Comment by vamshi9666** [comment]
facing same. i just used this for first time and when i ran example usage , i got this error

**Comment by Noukkis** [comment]
Also facing the same, reinstalling the module seems to temporally fix the issue but it reappears randomly
