### ISSUE TITLE
youtube-dl doesn't work [Error: spawn UNKNOWN]

### ISSUE THREAD

**Issue by DaniPani** [przemyslawpluta/node-youtube-dl#200]
This is my code:
```javascript
const loader = require('youtube-dl')
const fs = require('fs')

const video = loader('https://openload.co/f/Y4vQFIfNYdE/Mr.Robot.S01E01.Ciao.amico.1080p.mp4')

video.pipe(fs.createWriteStream('./files/video.mp4'))
```
But when I run it, I got this error (I even tried to use another link... http://www.youtube.com/watch?v=90AiXO1pAiA)
```javascript
internal/child_process.js:330
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at exports.spawn (child_process.js:500:9)
    at exports.execFile (child_process.js:210:15)
    at call (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\youtube-dl\lib\youtube-dl.js:163:5)
    at Function.getInfo (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\youtube-dl\lib\youtube-dl.js:285:5)
    at module.exports (C:\Users\danie\Google Drive\Projects WebSites\downloader\node_modules\youtube-dl\lib\youtube-dl.js:107:10)
    at Object.<anonymous> (C:\Users\danie\Google Drive\Projects WebSites\downloader\prove.js:4:15)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
```
Node v9.90
Windows 10
npm v5.60

**Comment by DaniPani** [comment]
Same as: https://github.com/przemyslawpluta/node-youtube-dl/issues/169
