### ISSUE TITLE
I am getting error at time of installing the module 

### ISSUE THREAD

**Issue by umar28dec** [przemyslawpluta/node-youtube-dl#201]
$ npm i youtube-dl

> youtube-dl@1.12.2 postinstall E:\node\video\youtube-downloader-app\node_modules\youtube-dl
> node ./scripts/download.js

E:\node\video\youtube-downloader-app\node_modules\youtube-dl\lib\downloader.js:20
        if (res.statusCode !== 302) {
                ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (E:\node\video\youtube-downloader-app\node_modules\youtube-dl\lib\downloader.js:20:17)
    at self.callback (E:\node\video\youtube-downloader-app\node_modules\request\request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (E:\node\video\youtube-downloader-app\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:371:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:174:19)
npm WARN youtube-downloader-app@0.1.0 No repository field.
npm WARN youtube-downloader-app@0.1.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@1.12.2 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl@1.12.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by Kikobeats** [comment]
this is still an error?
