### ISSUE TITLE
How to execute code after ytdl.exec() finishes downloading?   [question][help]

### ISSUE THREAD

**Issue by viktorhbk** [przemyslawpluta/node-youtube-dl#216]
I'm pretty new to node so please bear with me. 

I'm trying to make a web server with node and express to pipe videos to the client, here's the example:

```
const reqbody = {
  fps: '30',
  quality: '1080'
};
const url = 'https://www.youtube.com/watch?v=1La4QzGeaaQ';
const options =  ['-f', `bestvideo[fps=${reqbody.fps}][height<=${reqbody.quality}]+bestaudio`];
const video = ytdl(url, options);

  video.on("info", function(info) {
    res.set({
      "Content-Disposition": `attachment; filename=${info._filename}`,
    });

    video.pipe(res);
  });
```
Everything works well if I omit `+bestaudio` or `+bestvideo` in options. Once I include it I have the following error: 
```
url.js:150
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of
type string. Received type undefined
    at Url.parse (url.js:150:11)
    at Object.urlParse [as parse] (url.js:144:13)
    at processData (/mnt/e/projects/youtube-extractor/node_modules/youtube-dl/lib/youtube-dl.js:47:21)
    at getInfo (/mnt/e/projects/youtube-extractor/node_modules/youtube-dl/lib/youtube-dl.js:109:9)
    at done (/mnt/e/projects/youtube-extractor/node_modules/youtube-dl/lib/youtube-dl.js:295:9)
    at done (/mnt/e/projects/youtube-extractor/node_modules/youtube-dl/lib/youtube-dl.js:202:9)
    at ChildProcess.exithandler (child_process.js:279:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
```
~~I tried fiddling with `ytdl.exec()` function [as in this example](https://github.com/przemyslawpluta/node-youtube-dl/blob/master/example/best.js), and it downloads videos fine on server machine but since it doesn't return a stream I'm not sure how can I pass it to client.~~

How can I make this work ?

### Edit

I thought about it more and it's unlikely that it's possible to merge video and audio on the fly using `ytdl(url, options)`. If using `ytdl.exec()` is the only option, how do I wait till a file downloads and only then create a stream and pipe it to the client?

**Comment by viktorhbk** [comment]
Can't believe I haven't saw that `exec` function has a callback. Issue solved.
