### ISSUE TITLE
Error: Command failed: /root/MyApp/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=JPT3bFIwJYA /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by ImranBinShoukat** [przemyslawpluta/node-youtube-dl#220]
I am getting this error when trying to download youtube video.

```
Error: Command failed: /root/MyApp/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=JPT3bFIwJYA
/usr/bin/env: ‘python’: No such file or directory

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```
How can I fix this?

**Comment by thangl3** [comment]
I think you need install python on your OS
