### ISSUE TITLE
 Bug – ReferenceError: urls is not defined

### ISSUE THREAD

**Issue by Buzut** [przemyslawpluta/node-youtube-dl#230]
Hi! Thank you very much for this awesome module. Sometimes I get the following error:

```
ReferenceError: urls is not defined
    at done (/home/encoder/node_modules/@microlink/youtube-dl/lib/youtube-dl.js:82:38)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
```

Indeed, line 82, `urls` is never declared nor passed as a parameter. Seems that it's the last item in the `args` object, but I'm not sure whether it is always the case. So better not break anything.

**Comment by Kikobeats** [comment]
Thanks for the PR, maybe with https://github.com/przemyslawpluta/node-youtube-dl/pull/234 is enough?
