### ISSUE TITLE
When using a + for a format, a completely different error appears.

### ISSUE THREAD

**Issue by NeuronButter** [przemyslawpluta/node-youtube-dl#268]
So when I use `['-f', 'bestvideo']` or `['-f', 'best']`, everything works fine. But when using `['-f', 'bestvideo+bestaudio']` when the + symbol is used, this completely unrelated error occurs:
```
url.js:154
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:154:11)
    at Object.urlParse [as parse] (url.js:148:13)
    at processData (C:\Users\Neeron Bhatta\Documents\Coding\Hobul Downloader\Server\test\node_modules\@microlink\youtube-dl\lib\youtube-dl.js:67:17)
    at getInfo (C:\Users\Neeron Bhatta\Documents\Coding\Hobul Downloader\Server\test\node_modules\@microlink\youtube-dl\lib\youtube-dl.js:120:46)
    at done (C:\Users\Neeron Bhatta\Documents\Coding\Hobul Downloader\Server\test\node_modules\@microlink\youtube-dl\lib\youtube-dl.js:273:12)
    at done (C:\Users\Neeron Bhatta\Documents\Coding\Hobul Downloader\Server\test\node_modules\@microlink\youtube-dl\lib\youtube-dl.js:50:12)
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```
Umm, help?

**Comment by BrOrlandi** [comment]
Same problem here :(

**Comment by badalyan** [comment]
Anyone know a work-around?

**Comment by NeuronButter** [comment]
I believe it's not possible currently with this library. The reason being, that the original CLI creates 3 files, where as the JS library pipes the first one, then gets confused as to why there's more. Someone will need to build that feature directly into this library.

If you need a workaround, you could download Best Video and Best Audio, and then combine them with ffmpeg. A good example of this is https://github.com/fent/node-ytdl-core/blob/master/example/ffmpeg.js

**Comment by BrOrlandi** [comment]
It seems to be a problem when use something like bestvideo+bestaudio the youtube-dl should download 2 files, video and audio separated, but the lib only works with one single file for download.

The error occurs on `processData` method.
```js
const headers = Object.assign(
    { Host: url.parse(item.url).hostname },
    data.http_headers
  )
```

When using the format with `+` the `item.url` is undefined.

I also tried to download it with `youtubedl.exec`, the download works but the callback is called before the conversion finishes with error in stderror:
```
ERROR: unable to rename file: [Errno 2] No such file or directory
```

And the error message receive was:
```
Error: Command failed with exit code 1: /...project_path.../node_modules/youtube-dl/bin/youtube-dl --print-json --recode-video=mp4 http://www.youtube.com/watch?v=s4UhQ4hZzRM
```

#### What am I trying to do?
I was trying to download this video: `http://www.youtube.com/watch?v=s4UhQ4hZzRM` in 1080p mp4 format.

When I use `format=best[height<=1080]` it returns the video in 720p resolution even it has a 1080p resolution.
When I use `--recode-video=mp4 --format=bestvideo[height<=1080]+bestaudio` with youtube-dl on CLI, it works with the video in 1080p and MP4 format. The youtube-dl download an webm video and a m4a audio and merges into a .mkv file, then finally converts it to mp4.
