### ISSUE TITLE
Firebase Functions exit code 127

### ISSUE THREAD

**Issue by SwissCheese5** [przemyslawpluta/node-youtube-dl#269]
```Error: Command failed with exit code 127: /srv/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best http://www.youtube.com/watch?v=wbQsxWKfTSU
    at /srv/index.js:40:43
    at done (/srv/node_modules/youtube-dl/lib/youtube-dl.js:238:21)
    at done (/srv/node_modules/youtube-dl/lib/youtube-dl.js:24:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)```

Done while trying to getInfo:

```js
                    youtubedl.getInfo(originUrl, function (err, info) {
                        if (err) {
                            return reject(new Error(err));
                        }

                        console.log(`INFO: ${info}`);


                        const seconds = info._duration_raw;
                        const thumbnailUrl = `https://img.youtube.com/vi/${info.video_id}/mqdefault.jpg`;
                        const fullCoverUrl = `https://img.youtube.com/vi/${info.video_id}/maxresdefault.jpg`;
                        const trackName = info.title;
                        const trackURL = originUrl;
                        const channelID = info.channel;
                        const channelUrl = info.channel;
                        const channelAvatar = info.author.avatar;
                        const channelName = info.channel;
....```

I'm not sure why this happens. Doesn't exit code 127 mean it couldn't find the binary for youtube-dl.exe?

**Comment by au5ton** [comment]
I am also experiencing this issue and I'm not sure why.

**Comment by au5ton** [comment]
This might have something to do with it:

https://cloud.google.com/functions/docs/concepts/exec#file_system
> The function execution environment contains a runnable function file, plus files and directories included in the deployed function package such as local dependencies. These files are available in a read-only directory, which can be determined based on the function file location. Note that the function’s directory can be different than the current working directory.
> 
> ...
> 
> You can also load code from other files deployed with the function.
> 
> The only writeable part of the filesystem is the /tmp directory, which you can use to store temporary files in a function instance. This is a local disk mount point known as a "tmpfs" volume in which data written to the volume is stored in memory. Note that it will consume memory resources provisioned for the function.
> 
> The rest of the file system is read-only and accessible to the function.

**Comment by davidseek** [comment]
Same issue. Still trying to figure this out. Will post more, as soon as I know more.

**Comment by JamesShirazian** [comment]
@davidseek Any luck?

**Comment by davidseek** [comment]
Yes. 

The issue is, that firebase does not allow write on filesystem.
Therefore the traditional download of ffmpeg does not work.
Then I have added an executable properly using npm.
I got youtubedl working on functions, but then I was stuck with
payload size restrictions on functions.

For my scenario it was not possible to set everything up using functions.

I succeeded then setting everything up with a 
simple node.js Heroku environment.

From firebase functions I'm calling my Heroku env
via http and then I'm processing the 
result from Heroku in firebase functions.

It's not as convenient as everything through functions would have been,
but it was a pain in the ass to get to where I ended up at.
So safe yourself some time and just go with Heroku + functions.

**Comment by JamesShirazian** [comment]
@davidseek Thanks for the advice. It worked.

**Comment by lneninger** [comment]
how it worked for you?@davidseek

**Comment by luizcieslak** [comment]
If someone are trying to make this work with AWS Lambdas as I did, note that it is not possible due to the fact that nodejs environment does not have python package installed.

```sh
WARN	{ Error: Command failed: /opt/youtube-dl https://www.youtube.com/watch?v=_HSylqgVYQI
/usr/bin/env: python: No such file or directory

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 127,
  signal: null,
  cmd:
   '/opt/youtube-dl https://www.youtube.com/watch?v=_HSylqgVYQI' }
INFO	res /usr/bin/env: python: No such file or directory
```

as noted in #58 and #220 .

In AWS, this python removal seems recent. This [repo](https://github.com/widdix/aws-lambda-youtube-dl) wrapped this package in a lambda function but was archived in May this year due to this change.
