### ISSUE TITLE
ETIMEDOUT during download

### ISSUE THREAD

**Issue by friman** [przemyslawpluta/node-youtube-dl#289]
Hi
With some videos (for example: https://www.youtube.com/watch?v=yPn1W5_mvME) I am getting the follow error:
 
`events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: ETIMEDOUT
    at Timeout._onTimeout (/usr/share/webtvpro/client/libs/checker/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Emitted 'error' event on Readable instance at:
    at Readable.onevent (/usr/share/webtvpro/client/libs/checker/node_modules/streamify/lib/index.js:128:17)
    at Readable.emit (events.js:223:5)
    at Request.emit (events.js:223:5)
    at Timeout._onTimeout (/usr/share/webtvpro/client/libs/checker/node_modules/request/request.js:852:16)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'ETIMEDOUT',
  connect: true
}
`
I have already added 
       video.on('error', function error(err) {
            console.log('error 2:', err)
       })
but never capture it. 
How to handle it? Because after this error it just close whole node process.
thanks in advance

**Comment by yafp** [comment]
@friman 
i was willing to test but the example video is not available anymore.

**Comment by Kikobeats** [comment]
@yafp probably that's the error logged 😅
