### ISSUE TITLE
 The process stops if the video cannot be retrieved, for example because it has been deleted

### ISSUE THREAD

**Issue by VTFLAB** [przemyslawpluta/node-youtube-dl#291]
/dir/youtube-dl/lib/youtube-dl.js:82
    if (passOver && stdout === '' && urls.length > 1) {
                                     ^

ReferenceError: urls is not defined
    at done (/dir/youtube-dl/lib/youtube-dl.js:82:38)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by VTFLAB** [comment]
Add action if value does not exist before validating in if statement, very simple error.

    if (typeof urls !== 'undefined') {
      if (passOver && stdout === '' && urls.length > 1) {

**Comment by Kikobeats** [comment]
Can you make a PR?
