### ISSUE TITLE
Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by Dajust** [przemyslawpluta/node-youtube-dl#296]
I've been getting this error recently and it's consistent 
```
Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/home/justice/***/app/node_modules/request/request.js:816:19)
      at Object.onceWrapper (events.js:299:28)
      at ClientRequest.emit (events.js:210:5)
      at ClientRequest.EventEmitter.emit (domain.js:475:20)
      at TLSSocket.emitRequestTimeout (_http_client.js:690:9)
      at Object.onceWrapper (events.js:299:28)
      at TLSSocket.emit (events.js:210:5)
      at TLSSocket.EventEmitter.emit (domain.js:475:20)
      at TLSSocket.Socket._onTimeout (net.js:469:8)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```
I think this is related to [this request.js issues](https://github.com/request/request/issues/2676)

Node 12.*
Linux

**Comment by Dajust** [comment]
Sorry, I'm closing this issue as the error was a result of my misuse of the API.
I was using `video = youtubedl(url)` only for getting video info. Because I wasn't consuming the resulting stream, the server won't send more streams, that caused the request module to freakout.
