### ISSUE TITLE
Build failure on Heroku with 3.0.2

### ISSUE THREAD

**Issue by jjg77** [przemyslawpluta/node-youtube-dl#300]
/app/node_modules/youtube-dl/lib/get-binary.js:1
Error: ENOENT: no such file or directory, open '/app/node_modules/youtube-dl/bin/details'
at Object.openSync (fs.js:457:3)
at readFileSync (fs.js:359:35)
at module.exports (/app/node_modules/youtube-dl/lib/get-binary.js:15:30)
at Object.<anonymous> (/app/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
at Generator.next (<anonymous>)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)

**Comment by Haris87** [comment]
same issue
