### ISSUE TITLE
Unable to download certain videos

### ISSUE THREAD

**Issue by healzer** [przemyslawpluta/node-youtube-dl#301]
These used to work a few days ago, but now no longer works.
URL: https://www.youtube.com/watch?v=oGW1dRNc314
And: https://www.youtube.com/watch?v=oRSijEW_cDM

I am using the latest npm and youtube-dl version.

Code:
```
const good = 'YUcxj6IFoAo'
const bad = 'oRSijEW_cDM'

const fs = require('fs')
const youtubedl = require('youtube-dl')
 
const video = youtubedl('http://www.youtube.com/watch?v=' + bad,
  ['--format=18'],
  { cwd: __dirname })

video.on('info', function(info) {
  console.log('Download started')
  console.log('filename: ' + info._filename)
  console.log('size: ' + info.size)
})
 
video.pipe(fs.createWriteStream('myvideo.mp4'))

Error:
```
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: status code 403
    at Request.response (/var/www/html/discordvoice/node_modules/youtube-dl/lib/youtube-dl.js:71:35)
    at Request.emit (events.js:321:20)
    at Request.onRequestResponse (/var/www/html/discordvoice/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:321:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
Emitted 'error' event on Readable instance at:
    at Request.response (/var/www/html/discordvoice/node_modules/youtube-dl/lib/youtube-dl.js:71:21)
    at Request.emit (events.js:321:20)
    [... lines matching original stack trace ...]
    at readableAddChunk (_stream_readable.js:275:11)

```

```

**Comment by we-over-i** [comment]
Did you find any solution to this?

**Comment by ledlamp** [comment]
I'm getting this with https://www.youtube.com/watch?v=dQw4w9WgXcQ after updating the package which now has youtube-dl 2020.11.26. With previous version of youtube-dl, 2020.11.01.1 (and I think package version was the same) I got "ERROR: dQw4w9WgXcQ: YouTube said: Unable to extract video data"
