### ISSUE TITLE
Command failed when using youtubedl.exec() with [-x --audio-format mp3] options

### ISSUE THREAD

**Issue by PeacefulOtter** [przemyslawpluta/node-youtube-dl#303]
Hey,

I followed your example to get a node stream thanks to a youtube url. I've done the exact same thing as it's said, namely : 

let url = 'https://www.youtube.com/watch?v=' + VIDEO_ID
youtubedl.exec( url, [ '-x', '--audio-format', 'mp3' ], {}, function( err, output ) {
    if ( err ) throw err
    console.log( output.join( '\n' ) )
}

However, i always get the same error : 

(node:11136) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: path\to\node_modules\youtube-dl\bin\youtube-dl.exe -x --audio-format mp3 --encoding utf8 http://www.youtube.com/watch?v=VIDEO_ID
    at makeError (path\to\node_modules\youtube-dl\node_modules\execa\lib\error.js:56:11)
    at handlePromise (path\to\node_modules\youtube-dl\node_modules\execa\index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Am I doing anything wrong, or is it actually an issue ?
Thanks for your help !

**Comment by dustinvo17** [comment]
Hi @PeacefulOtter , did you find out the solution for this problem? I am currently facing this issue as well. If yes, would you please kindly suggest me how your approach was? Thank you very much

**Comment by PeacefulOtter** [comment]
Hello @dustinvo17 , I did not find any solution for this problem unfortunately. I've tried other approaches which all failed.. 
If you succeed to stream a video with a youtube url, please let me know!

**Comment by rzfzr** [comment]
Try ['--format=140'] as the options, only specifying the audio format, works for me, not using .exec tho
