### ISSUE TITLE
Installing NPM module in a Docker container, causes ENOENT

### ISSUE THREAD

**Issue by PermisosDev** [przemyslawpluta/node-youtube-dl#343]
the npm module is requesting the **WINDOWS** EXECUTABLE instead of the **LINUX** EXECUTABLE (Docker in this case.)
Docker FROM Image: ```node:14.0-alpine```
```
Error: Command failed with ENOENT: /usr/src/app/node_modules/youtube-dl/bin/youtube-dl.exe --dump-json --format=140 https://www.youtube.com/watch?v=yhS9LnDoo_w
2021-02-05 04:30:45.72 UTCspawn /usr/src/app/node_modules/youtube-dl/bin/youtube-dl.exe ENOENT
2021-02-05 04:30:45.72 UTC    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
2021-02-05 04:30:45.72 UTC    at onErrorNT (internal/child_process.js:468:16)
2021-02-05 04:30:45.72 UTC    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by PermisosDev** [comment]
Possible problematic line: https://github.com/przemyslawpluta/node-youtube-dl/blob/1b4e5a65447fcdbe7c7030925359cb045b5199a4/lib/downloader.js#L65

**Comment by ZeroTwoDev** [comment]
was this solved yet?

**Comment by PermisosDev** [comment]
> 
> 
> was this solved yet?

Use ytdl-core as alternative.

**Comment by PermisosDev** [comment]
> 
> 
> was this solved yet?

Use ytdl-core as alternative.
