### ISSUE TITLE
Missing ./node_modules/youtube-dl/bin/details file, postinstall script failing

### ISSUE THREAD

**Issue by Placni** [przemyslawpluta/node-youtube-dl#355]
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\MonkeyBot\MonkeyBot\main\node_modules\youtube-dl\bin\details'
    at Object.openSync (fs.js:462:3)
    at readFileSync (fs.js:364:35)
    at module.exports (C:\MonkeyBot\MonkeyBot\main\node_modules\youtube-dl\lib\get-binary.js:15:30)
    at Object.<anonymous> (C:\MonkeyBot\MonkeyBot\main\node_modules\youtube-dl\lib\youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\MonkeyBot\\MonkeyBot\\main\\node_modules\\youtube-dl\\bin\\details'
}

Updated npm, updated all packages, cleared npm cache. Still no dice. I haven't written any code using youtube-dl yet, this is just trying to import it

[2021-02-18T19_01_19_250Z-debug.log](https://github.com/przemyslawpluta/node-youtube-dl/files/6005162/2021-02-18T19_01_19_250Z-debug.log)
Added full debug log of `npm update`

```
node -v
v14.15.5
npm -v
v6.14.11
```

**Comment by Kikobeats** [comment]
do a refresh install, the `get-binary` doesn't exist on `3.4.0`, so I guess something is not fully download in your build

related: https://github.com/przemyslawpluta/node-youtube-dl/pull/352
