### ISSUE TITLE
3.4.0 Fails to install required deps

### ISSUE THREAD

**Issue by brennanwilkes** [przemyslawpluta/node-youtube-dl#356]
```internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'got'
Require stack:
- /usr/src/app/node_modules/youtube-dl/lib/youtube-dl.js
- /usr/src/app/build/backend/youtube/downloadURLToStream.js
- /usr/src/app/build/backend/controllers/songController.js
- /usr/src/app/build/backend/routes/v1.js
- /usr/src/app/build/backend/routes/index.js
- /usr/src/app/build/backend/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/youtube-dl/lib/youtube-dl.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/build/backend/youtube/downloadURLToStream.js:6:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/youtube-dl/lib/youtube-dl.js',
    '/usr/src/app/build/backend/youtube/downloadURLToStream.js',
    '/usr/src/app/build/backend/controllers/songController.js',
    '/usr/src/app/build/backend/routes/v1.js',
    '/usr/src/app/build/backend/routes/index.js',
    '/usr/src/app/build/backend/index.js'
  ]
}
```

**Comment by glococo** [comment]
same

**Comment by Nixinova** [comment]
Same issue, same error message. Installing 3.3.0 works fine.

**Comment by kennylbj** [comment]
+1
