### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by xemax76306** [przemyslawpluta/node-youtube-dl#358]
I can't understand what's going wrong. I attached log file.
[log.txt](https://github.com/przemyslawpluta/node-youtube-dl/files/6018113/log.txt)

**Comment by samuelcalegari** [comment]
exactly the same problem :(

**Comment by samuelcalegari** [comment]
try 
npm i --save --force youtube-dl

**Comment by Tejas12972** [comment]
still same issues

**Comment by Bawiani** [comment]
npm WARN using --force Recommended protections disabled.
npm WARN deprecated youtube-dl@3.5.0: node-youtube-dl is deprecated. use `npm.im/youtube-dl-exec` instead.
npm ERR! code 1
npm ERR! path C:\Users\Bawiani\Desktop\Projects\video-downloader-api\node_modules\youtube-dl
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run check && npm run download
npm ERR! > youtube-dl@3.5.0 check
npm ERR! > bin-version-check python '>=2'
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! Error: Invalid version range
npm ERR!     at module.exports (C:\Users\Bawiani\Desktop\Projects\video-downloader-api\node_modules\bin-version-check\index.js:12:25)
npm ERR!     at Object.<anonymous> (C:\Users\Bawiani\Desktop\Projects\video-downloader-api\node_modules\bin-version-check-cli\cli.js:29:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bawiani\AppData\Local\npm-cache\_logs\2023-06-18T21_48_54_159Z-debug-0.log

**Comment by Bawiani** [comment]
please, can someone help me out
